server:
  port: 80
spring:
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto:
            update
  mvc:
    favicon:
      enabled: false
  devtools:
    restart:
      enabled: true
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.outdd.toolbox.*.pojo

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


logging:
  level:
    com.outdd.toolbox.reptile.novel.dao: debug